name: Validate Website

on:
    pull_request:
        paths:
            - "docs/**"
    push:
        branches: ["main"]
        paths:
            - "docs/**"

jobs:
    validate:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Validate HTML
              uses: Cyb3r-Jak3/html5validator-action@v7.2.0
              with:
                  root: docs/

            - name: Check links
              uses: lycheeverse/lychee-action@v1
              with:
                  args: --verbose --no-progress 'docs/**/*.html'
                  fail: true
